- hosts: all
  gather_facts: false
  become: true
  tasks:
  - name: install wget
    yum:
      name: wget
      state: present
  - name: install openjdk
    yum:
      name: java-1.8.0-openjdk
      state: present
  - name: download jenkins.repo
    get_url:
      url: <mention the url>
      dest: /etc/yum.repos.d/jenkins.repo
  - name: import jenkins key 
    rpm_key:
      state: present
      key: <mention key url>
  - name: install jenkins
    yum:
      name: jenkins
      state: present
  - name: start jenkins
    systemd:
      name: jenkins
      state: started
  - name: enable jenkins
    systemd:
      name: jenkins
      enabled: true
  - name: sleep for 30 sec and continue with play
    wait_for:
      delay: 30
      port: 8080
  - name: init password jenkins
    shell: /var/lib/jenkins/secrets/initialAdminPassword
    change_when: false
    register: result
  - name: print init password jenkins
    debug: 
      var: result.stdout 
 
