- hosts: all
  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: present
      
  - name: copy index.html file 
    copy: 
      src: ~/index.html
      dest: /var/www/html/index.html
  
  handlers:
  - name: start nginx 
    service:
      name: nginx
      state: restarted
